### ISSUE TITLE
if a anylogger loggeris created after disabling (ulog.disable()) the disable state is not considered

### ISSUE THREAD

**Issue by wighawag** [Download/anylogger#13]
I do the the following in my webapp index.js
```js
import ulog from 'ulog';
// import anylogger from 'anylogger';
// anylogger('app:home');
ulog.disable('app:*');
```

and then in my home page
```js
import anylogger from 'anylogger';
const log = anylogger('app:home');
log.info('Anylogger is easy!');
```

if I leave the commented line commented, the log will appear, even though I wanted to disable all of them
If I instead comment out the 2 lines, it works as intended. 
Unfortunately this won't work if I use query string and it is also a shame to have to declare all loggers before hand

**Comment by Download** [comment]
Should be fixed. Please try with 1.0.7 or later and re-open if it still occurs.
