### ISSUE TITLE
Anylogger instance in library never outputs to console in application

### ISSUE THREAD

**Issue by MasterKale** [Download/anylogger#17]
I've implemented `anylogger` in a library I'm authoring in TypeScript. Unfortunately, the anylogger instance in my library is never updated by any adapters I try to use in an application (also TypeScript) that uses this library, so no logging in my library ever appears in the application's console output.

To keep things simple I'm using `import 'anylogger-console'` in the application that's consuming my library, but I also have this issue when I try with `ulog`.

I've created a repo reproducing the issue. The README.md file within contains basic reproduction steps:

https://github.com/MasterKale/anylogger-bug-repro-17

**Comment by Download** [comment]
@MasterKale 
Thank you for this bug report. I will investigate this as soon as I get some time. In the meantime you might consider investigating it yourself. Anylogger is quite a small script. But I will eventually pick this up.

**Comment by Download** [comment]
@MasterKale Reproduced your issue. Also have a suspicion of what may be happening.
Somehow 2 copies of anylogger are getting into the project I think. I'm not very well versed in Typescript but I made [a PR](https://github.com/MasterKale/anylogger-bug-repro-17/pull/1) that tests something, maybe it can help you find the problem.

**Comment by Download** [comment]
I was able to fix it, though maybe not in the way you want to...
Check [my latest PR](https://github.com/MasterKale/anylogger-bug-repro-17/pull/2) on the reproduction repo you made.

The symlinked module works differently from the regular modules. I guess symlinked in modules in NPM are still not working correctly. I consider this issue closed because I don't think there is much that `anylogger` can do about this. If you disagree, feel free to re-open.

**Comment by MasterKale** [comment]
Thank you for looking into this, what an odd idiosyncrasy of `npm` it has revealed. I apologize for not being more communicative while you troubleshot the problem, I was following your progress both here and on the PR and wasn't sure where best to provide any reactions 😅

I'll follow up in the PR. I hope you have a good weekend ✌️

**Comment by Download** [comment]
Hey MasterKale, no problem, that's just how it works with Open Source, sometimes people don't have time.

It's very unfortunate that NPM doesn;t support your setup the way it should. It would be really great if it did! I have tried many options but never got a satisfying setup with symlinking. But without it, it's very hard to develop a library as a real separate project from the application without having to publish after each change. The best way for now is to just include myLib as a folder in the actual application project I think and only factor it out into a separate project when the amount of changes it gets becomes smaller.

You could maybe report this as an issue to the NPM team. I guess it should not be impossible to make `require` aware of the fact that it's in a folder that's outside of node_modules and that it should check the node_modules it came from first.... But then again there is such a huge amount of issues on that project! But you have a pretty complete repro now so maybe it's worth a shot.
