### ISSUE TITLE
Install doesn't describe how to use on client side

### ISSUE THREAD

**Issue by wsargent** [Download/anylogger#4]
In the https://github.com/download/anylogger#install instructions, everything is written for NPM and server side javascript.  However, I'm using browser side Javascript and am a complete javascript newb, so I'm essentially using jQuery and nothing else.

How do I get anylogger set up and running with either debug or ulog?

**Comment by wsargent** [comment]
It looks like [going to the visionmedia github page](https://github.com/visionmedia/debug#readme) and downloading the javascript file, then adding the following to the index.html page does what I want:

```
<script type="text/javascript" src='/javascripts/anylogger.min.js")'></script>
<script type="text/javascript" src='/javascripts/debug.js")'></script>
```

And then in the main.js file:

```
debug.enable('page:main');
let logger = anylogger('page:main');
```

And then to get it to work in the browser, I have to use a [colon syntax](https://github.com/visionmedia/debug#browser-support):

```
debug.enable('browser:main')
let nlogger = anylogger('browser:network'); // no output
let logger = anylogger('browser:main'); // output
```

But I don't have to use the localstorage.debug method, because `debug.enable` will do the same thing?

Still a bit confused on where logger.trace vs logger.info goes in the browser as well.

**Comment by Download** [comment]
Sorry for the late response.
This project is a WIP and I build it in my spare time.
I hope to improve the readme for browser use before going to 1.0
I recommend not enabling / disabling in code, but in the config instead, yes.
So leave out the calls to `debug.enable`, then run `localStorage.setItem('debug', 'browser:main')` in the console, then refresh the page

I will leave this one open to remind me to update the docs. Thanks!

> Still a bit confused on where logger.trace vs logger.info goes in the browser as well.

Debug is *very* simple. It only has 1 log method. But anylogger supports more complex loggers as well. So every logger returned by anylogger has `info` etc methods. But if you are using anylogger with the anylogger-debug adapter, then all these methods are essentially the same method, the log function from debug.

**Comment by Download** [comment]
@wsargent 

I have updated the [`anylogger-debug`](https://npmjs.com/package/anylogger-debug) adapter with [instructions](https://www.npmjs.com/package/anylogger-debug#cdn) describing how to use `anylogger` and `debug` together, when loading files using script tags. Also, that project contains a `test.html` file that you can open in your browser. Clone the project and drag `test.html` to an open browser tab and it should open there.

I also added a new [`anylogger-loglevel`](https://npmjs.com/package/anylogger-loglevel) adapter, so you can experiment with switching logging frameworks between `debug` and `loglevel`. That adapter also has [instructions](https://www.npmjs.com/package/anylogger-debug#cdn) describing how to use  it when loading files using script tags and an `index.html` file that you can open in your browser. Clone the project and drag `index.html` to an open browser tab and it should open there.

Finally, I added a new [`anylogger-log4js`](https://npmjs.com/package/anylogger-log4js) adapter, but AFAICT log4js does not support browsers.

Please let me know if this helps you. 
Feel free to re-open this issue if you still have questions or problems.
